import type { Metadata } from "next";
import "../globals.css";
import { poppins } from "@/lib/font";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <div className="flex flex-col md:flex-row">
          <div className="md:w-1/2">{children}</div>
          <div className=" hidden bg-black md:w-1/2 md:flex justify-center items-center right-0 h-screen  fixed">
            <div className="relative">
              <div className="flex items-center justify-center flex-col border-white">
                <div className="mx-auto w-full  rounded-full flex items-center justify-center">
                  <Image
                    src="/uptrackLogoWhite.png"
                    alt="uptrackLogo"
                    width={500}
                    height={0}
                    className=" w-[100px] md:w-[500px] border-white"
                  />
                </div>
                <div className="hidden text-white/80 absolute top-5 p-2 rounded bg-gradient-to-tr from-black to-orange-700 backdrop-blur-sm right-[10]">
                  <p className="text">Small steps today, big wins tomorrow.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
